### ISSUE TITLE
Mystery Panic

### ISSUE THREAD

**Issue by Random-Liu** [BurntSushi/toml#211]
I don't understand why it panics. And after I remove all the primitive fields in `PluginConfig`, it works but generate wrong result.

```golang
package main

import (
	"github.com/BurntSushi/toml"
	"os"
)

// ContainerdConfig contains toml config related to containerd
type ContainerdConfig struct {
	// RootDir is the root directory path for containerd.
	// TODO(random-liu): Remove this field when no longer support cri-containerd standalone mode.
	RootDir string `toml:"root_dir" json:"rootDir,omitempty"`
	// Snapshotter is the snapshotter used by containerd.
	Snapshotter string `toml:"snapshotter" json:"snapshotter,omitempty"`
	// Endpoint is the containerd endpoint path.
	// TODO(random-liu): Remove this field when no longer support cri-containerd standalone mode.
	Endpoint string `toml:"endpoint" json:"endpoint,omitempty"`
	// Runtime is the runtime to use in containerd. We may support
	// other runtimes in the future.
	Runtime string `toml:"runtime" json:"runtime,omitempty"`
	// RuntimeEngine is the name of the runtime engine used by containerd.
	// Containerd default should be "runc"
	// We may support other runtime engines in the future.
	RuntimeEngine string `toml:"runtime_engine" json:"runtimeEngine,omitempty"`
	// RuntimeRoot is the directory used by containerd for runtime state.
	// Containerd default should be "/run/containerd/runc"
	RuntimeRoot string `toml:"runtime_root" json:"runtimeRoot,omitempty"`
}

// CniConfig contains toml config related to cni
type CniConfig struct {
	// NetworkPluginBinDir is the directory in which the binaries for the plugin is kept.
	NetworkPluginBinDir string `toml:"bin_dir" json:"binDir,omitempty"`
	// NetworkPluginConfDir is the directory in which the admin places a CNI conf.
	NetworkPluginConfDir string `toml:"conf_dir" json:"confDir,omitempty"`
}

// PluginConfig contains toml config related to CRI plugin,
// it is a subset of CRIConfig.
type PluginConfig struct {
	// ContainerdConfig contains config related to containerd
	ContainerdConfig `toml:"containerd" json:"containerd,omitempty"`
	// CniConfig contains config related to cni
	CniConfig `toml:"cni" json:"cni,omitempty"`
	// StreamServerAddress is the ip address streaming server is listening on.
	StreamServerAddress string `toml:"stream_server_address" json:"streamServerAddress,omitempty"`
	// StreamServerPort is the port streaming server is listening on.
	StreamServerPort string `toml:"stream_server_port" json:"streamServerPort,omitempty"`
	// EnableSelinux indicates to enable the selinux support.
	EnableSelinux bool `toml:"enable_selinux" json:"enableSelinux,omitempty"`
	// SandboxImage is the image used by sandbox container.
	SandboxImage string `toml:"sandbox_image" json:"sandboxImage,omitempty"`
	// StatsCollectPeriod is the period (in seconds) of snapshots stats collection.
	StatsCollectPeriod int `toml:"stats_collect_period" json:"statsCollectPeriod,omitempty"`
	// SystemdCgroup enables systemd cgroup support.
	SystemdCgroup bool `toml:"systemd_cgroup" json:"systemdCgroup,omitempty"`
	// SkipImageFSUUID skips retrieving imagefs uuid.
	// TODO(random-liu): Remove this after we find a generic way to get imagefs uuid.
	SkipImageFSUUID bool `toml:"skip_imagefs_uuid" json:"skipImageFSUUID,omitempty"`
	// EnableIPv6DAD enables IPv6 DAD.
	// TODO(random-liu): Use optimistic_dad when it's GA.
	EnableIPv6DAD bool `toml:"enable_ipv6_dad" json:"enableIPv6DAD,omitempty"`
}

// CRIConfig contains toml config related to CRI service.
// TODO(random-liu): Make this an internal config object when we no longer support cri-containerd
// standalone mode. At that time, we can clean this up.
type CRIConfig struct {
	// PluginConfig is the config for CRI plugin.
	PluginConfig
	// ContainerdRootDir is the root directory path for containerd.
	ContainerdRootDir string `toml:"-" json:"containerdRootDir,omitempty"`
	// ContainerdEndpoint is the containerd endpoint path.
	ContainerdEndpoint string `toml:"-" json:"containerdEndpoint,omitempty"`
	// SocketPath is the path to the socket which cri-containerd serves on.
	// TODO(random-liu): Remove SocketPath when no longer support cri-containerd
	// standalone mode.
	SocketPath string `toml:"socket_path" json:"socketPath,omitempty"`
	// RootDir is the root directory path for managing cri-containerd files
	// (metadata checkpoint etc.)
	RootDir string `toml:"root_dir" json:"rootDir,omitempty"`
}

// Config contains toml config related cri-containerd daemon.
type Config struct {
	CRIConfig
	// CgroupPath is the path for the cgroup that cri-containerd is placed in.
	CgroupPath string `toml:"cgroup_path"`
	// OOMScore adjust the cri-containerd's oom score
	OOMScore int `toml:"oom_score"`
	// EnableProfiling is used for enable profiling via host:port/debug/pprof/
	EnableProfiling bool `toml:"profiling"`
	// ProfilingPort is the port for profiling via host:port/debug/pprof/
	ProfilingPort string `toml:"profiling_port"`
	// ProfilingAddress is address for profiling via host:port/debug/pprof/
	ProfilingAddress string `toml:"profiling_addr"`
	// LogLevel is the logrus log level.
	LogLevel string `toml:"log_level"`
}

func main() {
	toml.NewEncoder(os.Stdout).Encode(Config{})
	return
}

```

Output:
```
panic: reflect: Field index out of bounds [recovered]
	panic: reflect: Field index out of bounds

goroutine 1 [running]:
github.com/BurntSushi/toml.(*Encoder).safeEncode.func1(0xc420045d68)
	/home/lantaol/workspace/src/github.com/BurntSushi/toml/encode.go:101 +0xa9
panic(0x4b32c0, 0x4e8590)
	/usr/local/go/src/runtime/panic.go:491 +0x283
reflect.(*structType).Field(0x4c84a0, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/type.go:1215 +0x248
reflect.(*rtype).Field(0x4c84a0, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/type.go:963 +0x8c
reflect.(*structType).FieldByIndex(0x4ca680, 0xc420014140, 0x2, 0x2, 0x4a492a, 0x9, 0x0, 0x0, 0x5472e0, 0x4c84a0, ...)
	/usr/local/go/src/reflect/type.go:1257 +0xb2
reflect.(*rtype).FieldByIndex(0x4ca680, 0xc420014140, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/type.go:971 +0xa6
github.com/BurntSushi/toml.(*Encoder).eStruct.func2(0xc42009e000, 0x12, 0x20)
	/home/lantaol/workspace/src/github.com/BurntSushi/toml/encode.go:349 +0x100
github.com/BurntSushi/toml.(*Encoder).eStruct(0xc420045df8, 0x574120, 0x0, 0x0, 0x4ca680, 0xc42009a000, 0x99)
	/home/lantaol/workspace/src/github.com/BurntSushi/toml/encode.go:374 +0x22d
github.com/BurntSushi/toml.(*Encoder).eMapOrStruct(0xc420045df8, 0x574120, 0x0, 0x0, 0x4ca680, 0xc42009a000, 0x99)
	/home/lantaol/workspace/src/github.com/BurntSushi/toml/encode.go:260 +0xaa
github.com/BurntSushi/toml.(*Encoder).eTable(0xc420045df8, 0x574120, 0x0, 0x0, 0x4ca680, 0xc42009a000, 0x99)
	/home/lantaol/workspace/src/github.com/BurntSushi/toml/encode.go:252 +0xbd
github.com/BurntSushi/toml.(*Encoder).encode(0xc420045df8, 0x574120, 0x0, 0x0, 0x4ca680, 0xc42009a000, 0x99)
	/home/lantaol/workspace/src/github.com/BurntSushi/toml/encode.go:149 +0x6d4
github.com/BurntSushi/toml.(*Encoder).safeEncode(0xc420045df8, 0x574120, 0x0, 0x0, 0x4ca680, 0xc42009a000, 0x99, 0x0, 0x0)
	/home/lantaol/workspace/src/github.com/BurntSushi/toml/encode.go:104 +0xac
github.com/BurntSushi/toml.(*Encoder).Encode(0xc420045df8, 0x4ca680, 0xc42009a000, 0xc42009a000, 0x1000)
	/home/lantaol/workspace/src/github.com/BurntSushi/toml/encode.go:88 +0xca
main.main()
	/home/lantaol/workspace/src/github.com/random-liu/test1/test.go:102 +0x183
```

**Comment by arp242** [comment]
I tried your code and it doesn't seem to panic now. I think this got fixed in #251. Let me know if there are still are problems.
