### ISSUE TITLE
Encode panics when it encounters a newtype of a complex number even if it implements TextMarshaler

### ISSUE THREAD

**Issue by coriolinus** [BurntSushi/toml#223]
Consider the following example. We implement our own type as a newtype around `complex128`, and implemente `TextMarshaler` so that we can specify how to encode it into TOML. 

```go
package main

import (
	"bytes"
	"encoding"
	"fmt"
	"os"

	"github.com/BurntSushi/toml"
)

func check(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

type Complex complex128

// static assert that we've successfully implemented encoding.TextMarshaler
var _ encoding.TextMarshaler = (*Complex)(nil)

func (c Complex) MarshalText() ([]byte, error) {
	cplx := complex128(c)
	return []byte(fmt.Sprintf("(%f+%fi)", real(cplx), imag(cplx))), nil
}

func main() {
	consts := make(map[string]interface{})
	consts["i"] = Complex(complex(0.0, 1.0))

	buf := new(bytes.Buffer)
	err := toml.NewEncoder(buf).Encode(consts)
	check(err)
	fmt.Println(buf.String())
}
```

This should produce the following output: `i = "(0.0+1.0i)"`

Instead, we get this:

```sh
$ go build ./cmd/bugreport/ && ./bugreport
panic: unexpected reflect.Kind: complex128 [recovered]
        panic: unexpected reflect.Kind: complex128

goroutine 1 [running]:
github.com/oneiro-ndev/binary-serializer-experiment/vendor/github.com/BurntSushi/toml.(*Encoder).safeEncode.func1(0xc420041e98)
        /home/coriolinus/projects/go/src/github.com/oneiro-ndev/binary-serializer-experiment/vendor/github.com/BurntSushi/toml/encode.go:101 +0xa9
panic(0x4b3fa0, 0xc42000e340)
        /usr/lib/go-1.9/src/runtime/panic.go:491 +0x283
github.com/oneiro-ndev/binary-serializer-experiment/vendor/github.com/BurntSushi/toml.tomlTypeOfGo(0x4ba840, 0x4e8fe0, 0x90, 0x4ba840, 0x4e8fe0)
        /home/coriolinus/projects/go/src/github.com/oneiro-ndev/binary-serializer-experiment/vendor/github.com/BurntSushi/toml/encode.go:420 +0x547
github.com/oneiro-ndev/binary-serializer-experiment/vendor/github.com/BurntSushi/toml.tomlTypeOfGo(0x4ba7e0, 0xc42000e330, 0x94, 0x4b3fa0, 0xc42000e320)
        /home/coriolinus/projects/go/src/github.com/oneiro-ndev/binary-serializer-experiment/vendor/github.com/BurntSushi/toml/encode.go:405 +0x28a
github.com/oneiro-ndev/binary-serializer-experiment/vendor/github.com/BurntSushi/toml.(*Encoder).eMap(0xc420041f50, 0x5761a0, 0x0, 0x0, 0x4bbde0, 0xc42006a150, 0x15)
        /home/coriolinus/projects/go/src/github.com/oneiro-ndev/binary-serializer-experiment/vendor/github.com/BurntSushi/toml/encode.go:277 +0x218
github.com/oneiro-ndev/binary-serializer-experiment/vendor/github.com/BurntSushi/toml.(*Encoder).eMapOrStruct(0xc420041f50, 0x5761a0, 0x0, 0x0, 0x4bbde0, 0xc42006a150, 0x15)
        /home/coriolinus/projects/go/src/github.com/oneiro-ndev/binary-serializer-experiment/vendor/github.com/BurntSushi/toml/encode.go:258 +0xef
github.com/oneiro-ndev/binary-serializer-experiment/vendor/github.com/BurntSushi/toml.(*Encoder).eTable(0xc420041f50, 0x5761a0, 0x0, 0x0, 0x4bbde0, 0xc42006a150, 0x15)
        /home/coriolinus/projects/go/src/github.com/oneiro-ndev/binary-serializer-experiment/vendor/github.com/BurntSushi/toml/encode.go:252 +0xbd
github.com/oneiro-ndev/binary-serializer-experiment/vendor/github.com/BurntSushi/toml.(*Encoder).encode(0xc420041f50, 0x5761a0, 0x0, 0x0, 0x4bbde0, 0xc42006a150, 0x15)
        /home/coriolinus/projects/go/src/github.com/oneiro-ndev/binary-serializer-experiment/vendor/github.com/BurntSushi/toml/encode.go:142 +0x584
github.com/oneiro-ndev/binary-serializer-experiment/vendor/github.com/BurntSushi/toml.(*Encoder).safeEncode(0xc420041f50, 0x5761a0, 0x0, 0x0, 0x4bbde0, 0xc42006a150, 0x15, 0x0, 0x0)
        /home/coriolinus/projects/go/src/github.com/oneiro-ndev/binary-serializer-experiment/vendor/github.com/BurntSushi/toml/encode.go:104 +0xac
github.com/oneiro-ndev/binary-serializer-experiment/vendor/github.com/BurntSushi/toml.(*Encoder).Encode(0xc420041f50, 0x4bbde0, 0xc42006a150, 0xc420080000, 0x1000)
        /home/coriolinus/projects/go/src/github.com/oneiro-ndev/binary-serializer-experiment/vendor/github.com/BurntSushi/toml/encode.go:88 +0xca
main.main()
        /home/coriolinus/projects/go/src/github.com/oneiro-ndev/binary-serializer-experiment/cmd/bugreport/main.go:33 +0x1eb
```

**Comment by arp242** [comment]
This was a bit of an edge case as `complex128` isn't a type that TOML (and therefore, this library) supports. It works for all other types, just not this one (and also `func` and `chan` types, but why you would want to marshal those ... I don't know).

At any rate, it's fixed now
