### ISSUE TITLE
Unmarshal into struct does not work with custom UnmarshalText

### ISSUE THREAD

**Issue by cenkalti** [BurntSushi/toml#231]
I expect this to work but it doesn't:
```go
package main

import (
	"fmt"
	"log"

	"github.com/BurntSushi/toml"
)

type Config struct {
	Values map[string]*Type `toml:"values"`
}

type Type struct {
	i interface{}
}

func (t *Type) UnmarshalText(text []byte) error {
	t.i = "baz"
	return nil
}

func main() {
	s := `
	[values]
	foo = "bar"
	`
	var c Config
	if err := toml.Unmarshal([]byte(s), &c); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("Database: %#v\n", c.Values)
}
```

Output:
```
[kipple:_examples]{master}% go run example.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10bbaf7]

goroutine 1 [running]:
main.(*Type).UnmarshalText(0x0, 0xc000018130, 0x3, 0x8, 0x3, 0x8)
	/Users/cenk/go/src/github.com/BurntSushi/toml/_examples/example.go:19 +0x27
github.com/BurntSushi/toml.(*MetaData).unifyText(0xc000091e20, 0x10cd900, 0xc00000e3f0, 0x1270020, 0x0, 0x1, 0x1085e29)
	/Users/cenk/go/src/github.com/BurntSushi/toml/decode.go:464 +0x156
github.com/BurntSushi/toml.(*MetaData).unify(0xc000091e20, 0x10cd900, 0xc00000e3f0, 0x10d5c80, 0xc00000c040, 0x196, 0x1, 0x2)
	/Users/cenk/go/src/github.com/BurntSushi/toml/decode.go:183 +0x9b1
github.com/BurntSushi/toml.(*MetaData).unifyMap(0xc000091e20, 0x10d53a0, 0xc000062210, 0x10d5160, 0xc00000c028, 0x195, 0xc000091a60, 0x8)
	/Users/cenk/go/src/github.com/BurntSushi/toml/decode.go:296 +0x4dd
github.com/BurntSushi/toml.(*MetaData).unify(0xc000091e20, 0x10d53a0, 0xc000062210, 0x10d5160, 0xc00000c028, 0x195, 0x0, 0x1)
	/Users/cenk/go/src/github.com/BurntSushi/toml/decode.go:211 +0x772
github.com/BurntSushi/toml.(*MetaData).unifyStruct(0xc000091e20, 0x10d53a0, 0xc000062180, 0x10d9b40, 0xc00000c028, 0x199, 0x10d8920, 0x10c8200)
	/Users/cenk/go/src/github.com/BurntSushi/toml/decode.go:265 +0x6ae
github.com/BurntSushi/toml.(*MetaData).unify(0xc00006ae20, 0x10d53a0, 0xc000062180, 0x10d9b40, 0xc00000c028, 0x199, 0x100ac8f, 0xc0000180c0)
	/Users/cenk/go/src/github.com/BurntSushi/toml/decode.go:209 +0x800
github.com/BurntSushi/toml.Decode(0xc00001a180, 0x19, 0x10c8200, 0xc00000c028, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/cenk/go/src/github.com/BurntSushi/toml/decode.go:123 +0x3cb
github.com/BurntSushi/toml.Unmarshal(0xc00006af40, 0x19, 0x20, 0x10c8200, 0xc00000c028, 0x20, 0x10d9801)
	/Users/cenk/go/src/github.com/BurntSushi/toml/decode.go:25 +0x8a
main.main()
	/Users/cenk/go/src/github.com/BurntSushi/toml/_examples/example.go:29 +0xa4
exit status 2
```

**Comment by cenkalti** [comment]
I use https://github.com/naoina/toml . It does not have the same problem.

**Comment by nkuba** [comment]
Same problem here.

It passes `nil` as `v` to `unifyText`:
https://github.com/BurntSushi/toml/blob/3012a1dbe2e4bd1391d42b32f0577cb7bbc7f005/decode.go#L182-L184

**Comment by arp242** [comment]
I think this is the same problem as #223? I'll get it fixed later this week. In the meanwhile, I'll close this as a duplicate.

**Comment by AImager** [comment]
it still panic in v1.1.0
