### ISSUE TITLE
Cannot round trip strings containing "\u"

### ISSUE THREAD

**Issue by ChrisHines** [BurntSushi/toml#66]
Steps to reproduce:

1. Run this code:

```go
package main

import (
	"bytes"
	"fmt"

	"github.com/BurntSushi/toml"
)

func main() {
	data := map[string]string{
		"k": `c:\users`,
	}

	buf := &bytes.Buffer{}
	enc := toml.NewEncoder(buf)
	if err := enc.Encode(data); err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(buf.String())
	data2 := make(map[string]string)
	if _, err := toml.DecodeReader(buf, &data2); err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(data2)
}
```

I expect it to run without error and result in `data2` containing a copy of `data`.

Instead I get this output:

```
k = "c:\\users"

2015/01/16 11:05:00 BUG: Could not parse 'sers' as a hexadecimal number, but the lexer claims it's OK: strconv
.ParseUint: parsing "sers": invalid syntax
```

and the program aborts before completing.

**Comment by ChrisHines** [comment]
This seems to be a bug on the parsing side.

```go
package main

import (
	"fmt"

	"github.com/BurntSushi/toml"
)

func main() {
	data := `k = "\\u"`
	m := make(map[string]string)
	if _, err := toml.Decode(data, &m); err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(m)
}
```

The above code should print `map[k:\u]` (try it with `\\p` for comparison), but it panics instead.

```
panic: runtime error: slice bounds out of range [recovered]
        panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/BurntSushi/toml.func·007()
        C:/gopath/src/github.com/BurntSushi/toml/parse.go:47 +0xf4
github.com/BurntSushi/toml.(*parser).replaceUnicode(0xc0820180e0, 0xc08200a3ec, 0x2, 0x0, 0x0)
        C:/gopath/src/github.com/BurntSushi/toml/parse.go:422 +0x1fd
github.com/BurntSushi/toml.(*parser).value(0xc0820180e0, 0x4, 0xc08200a405, 0x3, 0x1, 0x0, 0x0, 0x0, 0x0)
        C:/gopath/src/github.com/BurntSushi/toml/parse.go:151 +0xda
github.com/BurntSushi/toml.(*parser).topLevel(0xc0820180e0, 0x12, 0xc08200a400, 0x0, 0x1)
        C:/gopath/src/github.com/BurntSushi/toml/parse.go:135 +0xac3
github.com/BurntSushi/toml.parse(0x5292d0, 0x9, 0xc0820180e0, 0x3b1bd8, 0xc08200a440)
        C:/gopath/src/github.com/BurntSushi/toml/parse.go:63 +0x4cc
github.com/BurntSushi/toml.Decode(0x5292d0, 0x9, 0x4cb9e0, 0xc082046018, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/gopath/src/github.com/BurntSushi/toml/decode.go:106 +0x71
main.main()
        C:/gopath/src/comscore/borg-queen/cmd/toml-test/toml-test.go:12 +0xd6
```
